### ISSUE TITLE
Getting "index.html doesn't exist in archive" when creating PDF from static html

### ISSUE THREAD

**Issue by Aracif** [adobe/pdfservices-java-sdk-samples#50]
### Expected Behaviour
An extremely basic  PDF to be generated.

### Actual Behaviour
The error
`com.adobe.pdfservices.operation.exception.ServiceApiException: description ='index.html doesn't exist in archive.; requestId=341e7228-c0f5-4d5f-8fe2-bb1cd2a85587'; requestTrackingId='341e7228-c0f5-4d5f-8fe2-bb1cd2a85587'; statusCode=400; errorCode=MISSING_INDEX_HTML
	at com.adobe.pdfservices.operation.internal.api.PlatformApi.statusPoll(PlatformApi.java:115)
	at com.adobe.pdfservices.operation.pdfops.CreatePDFOperation.execute(CreatePDFOperation.java:209)`

### Reproduce Scenario (including but not limited to)
I've attached the zip

#### Steps to Reproduce
Create an html file called index.html with this content

```
<!DOCTYPE html>
 <html lang="en">
 
 <head>
     <meta charset="UTF-8">
     <title>basic</title>
 </head>
 
 <body>
     <h1>TEST</h1>
 </body>
 
 </html>
```

Then use this example provided on the git page to create a PDF [https://github.com/adobe/pdfservices-java-sdk-samples/blob/release_3.5.1/src/main/java/com/adobe/pdfservices/operation/samples/createpdf/CreatePDFFromStaticHTML.java](url)

#### Platform and Version
pdfservices-sdk 3.5.1 with Java 8

#### Sample Code that illustrates the problem
Create an html file called index.html with this content
```
<!DOCTYPE html>
 <html lang="en">
 
 <head>
     <meta charset="UTF-8">
     <title>basic</title>
 </head>
 
 <body>
     <h1>TEST</h1>
 </body>
 
 </html>
```
Then use this example provided on the git page to create a PDF [https://github.com/adobe/pdfservices-java-sdk-samples/blob/release_3.5.1/src/main/java/com/adobe/pdfservices/operation/samples/createpdf/CreatePDFFromStaticHTML.java](url)
[example.zip](https://github.com/adobe/pdfservices-java-sdk-samples/files/14961584/example.zip)

**Comment by Aracif** [comment]
[example.zip](https://github.com/adobe/pdfservices-java-sdk-samples/files/14961616/example.zip)

**Comment by JoelGeraci** [comment]
index.html has to be at the top level of the .zip not inside a folder. Like this one 
[example_2.zip](https://github.com/adobe/pdfservices-java-sdk-samples/files/14967616/example_2.zip)

**Comment by Aracif** [comment]
Thanks Joel you are correct. That was a dumb mistake on my part, appreciate u taking the time to help.

**Comment by hitesh-kumar-mahour** [comment]
Closing this issue since it has been idle since long. Please feel free to reopen the issue if required.
